### ISSUE TITLE
Exception when called on a single hash

### ISSUE THREAD

**Issue by tpbowden** [tpbowden/backdrop#2]
Backdrop.load({})
TypeError: can't convert nil into String
from /Users/tom/projects/backdrop/lib/backdrop/api_builder.rb:33:in `join'

**Comment by tpbowden** [comment]
@benthorner Any suggestions? Looks like you caused the bug I'm afraid. I am leaning towards removing the backdrop_url attribute behaviour in favour of only using the Backdrop.load argument.

**Comment by tpbowden** [comment]
Added some failing specs on 9fd644396226a20360e251e075d6be0e80878bd7

**Comment by benthorner** [comment]
@tpbowden Hi Tom. The exception is unavoidable: you're not specifying the backdrop URL (either implicitly or explicitly). The 'it' description for that test is inconsistent with the test (Line 23 - what URL?).

**Comment by benthorner** [comment]
I think deprecating backdrop_url is a good idea. I've always used the explicit version of .load, and there seem to be few cases when there is just one URL for something (especially on members).

**Comment by benthorner** [comment]
@tpbowden Would you like me to help with this?

**Comment by tpbowden** [comment]
Thanks. No I don't mind sorting it I just wanted an opinion. I'll look into
it tomorrow see what happens
