### ISSUE TITLE
Method to set HTTP Response codes

### ISSUE THREAD

**Issue by tpbowden** [tpbowden/backdrop#4]
I've implemented it in backdropjs but not in here yet because I'm not sure if its the cleanest way to do it. My idea was when `Backdrop.status(500, '/somewhere')` is called, a file called `somewhere.code` with the content `500` is written alongside any JSON that is there in `somewhere.json`. That way the old behaviour is unchanged and the web server just has to check for a corresponding `.code` file or return the usual 200/404.

**Comment by tpbowden** [comment]
@benthorner thoughts?

**Comment by benthorner** [comment]
Since a response can have other fields, I think it makes more sense to put the code in a hash in the same file (even if you then have to parse and re-serialize the data).

**Comment by benthorner** [comment]
Otherwise it makes sense, except Backdrop.status sounds like a question. How about Backdrop.stub?

**Comment by tpbowden** [comment]
Hmm yeah i guess it wouldn't be too hard to make all files be a hash that looks something like this;

    { 'meta_data': { 'code': 500, 'headers: {} etc. }, 'data': { json here } }

I also thing it might be better to have Backdrop.load accept 2 args, a URL and then just a hash with the config in it (including the JSON since thats now optional too)

**Comment by benthorner** [comment]
Yup - so you could just store the hash directly, and behave gracefully depending on whether it has a 'data' field and/or a 'code' field.
